// Generated by Wrangler by running `wrangler types src/server/env.d.ts --env-interface CfEnv`

export interface CfEnv {
	ENV: string;
	AUTH_SESSION_SECRET_KEY: string;
	DOCS_USER: string;
	DOCS_PASSWORD: string;
	DOCS_REALM: string;
	ADMIN_USER: string;
	ADMIN_PASSWORD: string;
	TURNSTILE_SECRET_KEY: string;
	CF_ACCOUNT_ID: string;
	CF_TOKEN: string;
	DB: D1Database;
}
