name="cloudfire"
compatibility_date="2024-06-14"
pages_build_output_dir="./dist"

[[d1_databases]]
binding="DB" # i.e. available in your Worker on env.DB
database_name="cloudfire-prod-db"
database_id="496d869e-c40c-4638-8a49-e3364a6f50f8"
preview_database_id="DB"
migrations_dir="./server/lib/db/migrations"

[env.preview]
name="preview"
[[env.preview.d1_databases]]
binding="DB"
database_name="cloudfire-preview-db"
database_id="d6705e69-13de-4c7d-8252-30f354066758"
migrations_dir="./server/lib/db/migrations"
